# Generated by Django 5.1 on 2024-08-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0002_remove_feedback_auditorium'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
