# Generated by Django 5.1 on 2024-08-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0002_alter_feedback_auditorium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='auditorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorium.auditorium'),
        ),
    ]
